In [1]:
# numpyインポート
import numpy as np
# a,b行列格納
a = np.array([[0, 1], [2, 3], [4, 5]])
b = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
# a * b
product = np.dot(a, b)
# a * b の結果
print(product)
# a * b の最大値
print(product.max())

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
